version: '2'
services:
  discovery:
    container_name: discovery
    build:
      context: discovery
      dockerfile: Dockerfile
    image: giga/discovery:0.0.1-SNAPSHOT
    ports:
      - 127.0.0.1:8761:8761
    networks:
      - spring-cloud-network
#  config:
#    container_name: config
#    build:
#      context: config
#      dockerfile: Dockerfile
#    image: giga/config:0.0.1-SNAPSHOT
#    volumes:
#      - ./config-data:/var/config-data
#    environment:
#      - JAVA_OPTS=
#        -DEUREKA_SERVER=http://discovery:8761/eureka
#        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
#
#    depends_on:
#      - discovery
#
#    ports:
#      - 127.0.0.1:8888:8888
#    networks:
#      - spring-cloud-network

  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    volumes:
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
    #    networks:
    #      elemento:
    #        ipv4_address: 172.26.1.2
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_USER=enrico
      - POSTGRES_DB=museek_db
      - POSTGRES_PASSWORD=enrico
    networks:
      - spring-cloud-network

  museek:
    container_name: museek
    build:
      context: museek
      dockerfile: Dockerfile
    image: giga/museek:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
#      - JAVA_OPTS=
#        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    networks:
      - spring-cloud-network

  museek_gateway:
    container_name: museek_gateway
    build:
      context: museek_gateway
      dockerfile: Dockerfile
    image: giga/museek_gateway:0.0.1-SNAPSHOT
    ports:
      - 127.0.0.1:8090:8090
    environment:
      - JAVA_OPTS=
        -Dapplication.jwt.secretKey=securesecuresecuresecuresecuresecuresecuresecure
      - PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/museek_db
      - SPRING_DATASOURCE_PASSWORD=enrico
      - SPRING_DATASOURCE_USERNAME=enrico
      - MUSEEK_URL=http://museek:8080
      - DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - HOST_PORT=http://127.0.0.1:8090
      - EUREKA_SERVER=http://discovery:8761/eureka


    networks:
      - spring-cloud-network
    depends_on:
      - discovery
      - postgres_db
      - museek
networks:
  spring-cloud-network:
    driver: bridge